/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddNewProblemPage.java
 *
 * Created on Aug 22, 2012, 11:28:23 PM
 */
package pencon;

import javax.swing.JOptionPane;

/**
 *
 * @author RATUL
 */
public class AddNewProblemPage extends javax.swing.JDialog {
    
    /*adding new problem*/
    void addProblem(){
        ProblemSet problemSet = new ProblemSet();
        
        //adding problem
        if( problemSet.addUpdateProblem(problemSet.getRecentProblemId(), jTextFieldName.getText(), jTextFieldInputFile.getText(), 
                jTextFieldOutputFile.getText(), jTextFieldTimeLimit.getText(), jTextFieldMemoryLimit.getText())==true ){
            JOptionPane.showMessageDialog(rootPane, "New problem added.", "Successful", JOptionPane.INFORMATION_MESSAGE);

            //clearing value of all fields
            jTextFieldName.setText(null);
            jTextFieldInputFile.setText(null);
            jTextFieldOutputFile.setText(null);
            jTextFieldTimeLimit.setText(null);
            jTextFieldMemoryLimit.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "You did not give correct information.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //set new title
        setTitle("Problem "+String.valueOf(problemSet.getRecentProblemId()));
    }
    
    /** Creates new form AddNewProblemPage */
    public AddNewProblemPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        //determine problem ID
        ProblemSet problemSet = new ProblemSet();
        char problemSerial = problemSet.getRecentProblemId();
        setTitle("Problem "+String.valueOf(problemSerial));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTimeLimitUnit = new javax.swing.JLabel();
        jLabelMemoryLimitUnit = new javax.swing.JLabel();
        jButtonInputFileBrwose = new javax.swing.JButton();
        jButtonOutputFileBrwose = new javax.swing.JButton();
        jTextFieldTimeLimit = new javax.swing.JTextField();
        jTextFieldMemoryLimit = new javax.swing.JTextField();
        jTextFieldInputFile = new javax.swing.JTextField();
        jTextFieldOutputFile = new javax.swing.JTextField();
        jButtonFinish = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jLabelMemoryLimit = new javax.swing.JLabel();
        jLabelTimeLimit = new javax.swing.JLabel();
        jLabelNameOutputFile = new javax.swing.JLabel();
        jLabelNameInputFile = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelTimeLimitUnit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelTimeLimitUnit.setText("Sec");

        jLabelMemoryLimitUnit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelMemoryLimitUnit.setText("KB");

        jButtonInputFileBrwose.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButtonInputFileBrwose.setText("Brwose");
        jButtonInputFileBrwose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputFileBrwoseActionPerformed(evt);
            }
        });

        jButtonOutputFileBrwose.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButtonOutputFileBrwose.setText("Brwose");
        jButtonOutputFileBrwose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputFileBrwoseActionPerformed(evt);
            }
        });

        jTextFieldTimeLimit.setFont(new java.awt.Font("Tahoma", 0, 14));

        jTextFieldMemoryLimit.setFont(new java.awt.Font("Tahoma", 0, 14));

        jTextFieldInputFile.setFont(new java.awt.Font("Tahoma", 0, 14));

        jTextFieldOutputFile.setFont(new java.awt.Font("Tahoma", 0, 14));

        jButtonFinish.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonFinish.setText("Finish");
        jButtonFinish.setFocusPainted(false);
        jButtonFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonAdd.setText("Add");
        jButtonAdd.setFocusPainted(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabelMemoryLimit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelMemoryLimit.setText("Memory Limit :");

        jLabelTimeLimit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelTimeLimit.setText("Time Limit      :");

        jLabelNameOutputFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNameOutputFile.setText("Output File     :");

        jLabelNameInputFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNameInputFile.setText("Input File        :");

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelName.setText("Name             :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNameInputFile)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInputFileBrwose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMemoryLimit)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMemoryLimitUnit, 0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelTimeLimit)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelTimeLimitUnit, 0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabelNameOutputFile)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonOutputFileBrwose)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameInputFile)
                    .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInputFileBrwose))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameOutputFile)
                    .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOutputFileBrwose))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTimeLimit)
                    .addComponent(jTextFieldTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTimeLimitUnit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMemoryLimit)
                    .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMemoryLimitUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonFinish)
                    .addComponent(jButtonCancel))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonInputFileBrwoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputFileBrwoseActionPerformed
    FileDirectory fileDirectory = new FileDirectory();
    String inPath = fileDirectory.selectFile("Select", "(input file)");
    jTextFieldInputFile.setText(inPath);
}//GEN-LAST:event_jButtonInputFileBrwoseActionPerformed

private void jButtonOutputFileBrwoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputFileBrwoseActionPerformed
    FileDirectory fileDirectory = new FileDirectory();
    String outPath = fileDirectory.selectFile("Select", "(output file)");
    jTextFieldOutputFile.setText(outPath);
}//GEN-LAST:event_jButtonOutputFileBrwoseActionPerformed

private void jButtonFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinishActionPerformed
    addProblem();
    dispose();
}//GEN-LAST:event_jButtonFinishActionPerformed

private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
    addProblem();
}//GEN-LAST:event_jButtonAddActionPerformed

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddNewProblemPage dialog = new AddNewProblemPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonFinish;
    private javax.swing.JButton jButtonInputFileBrwose;
    private javax.swing.JButton jButtonOutputFileBrwose;
    private javax.swing.JLabel jLabelMemoryLimit;
    private javax.swing.JLabel jLabelMemoryLimitUnit;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameInputFile;
    private javax.swing.JLabel jLabelNameOutputFile;
    private javax.swing.JLabel jLabelTimeLimit;
    private javax.swing.JLabel jLabelTimeLimitUnit;
    private javax.swing.JTextField jTextFieldInputFile;
    private javax.swing.JTextField jTextFieldMemoryLimit;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldOutputFile;
    private javax.swing.JTextField jTextFieldTimeLimit;
    // End of variables declaration//GEN-END:variables
}
