/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 * Created on Mar 6, 2012, 10:57:46 PM
 */
package pencon;

import java.awt.Color;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author RATUL
 */
public class PasswordChange extends javax.swing.JFrame {
    
    String mainPath = "C:\\Program Files\\PenCon";
    String passwordPath = mainPath + "\\Password";
    
    boolean checkPassword(){
        //taking input from user password
        String newPassword = new String(jPasswordFieldNewPassword.getPassword());
        String rePassword = new String(jPasswordFieldRePassword.getPassword());
        return newPassword.equals(rePassword);
    }
    
    /*checking the one of character exist in string*/
    boolean checkString(String sample, char start, char end){
        for(int I=0; I<sample.length(); I++){
            char ch = sample.charAt(I);
            if( ch>=start&&ch<=end )
                return true;
        }
        return false;
    }
    
    /** Creates new form PasswordChange */
    public PasswordChange() {
        initComponents();
        setLocationRelativeTo(null);     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNewName = new javax.swing.JTextField();
        jLabelNewName = new javax.swing.JLabel();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jLabelNewPassword = new javax.swing.JLabel();
        jPasswordFieldRePassword = new javax.swing.JPasswordField();
        jLabelRePassword = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelRePasswordStatus = new javax.swing.JLabel();
        jLabelNewPasswordStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Password Change");
        setResizable(false);

        jTextFieldNewName.setFont(new java.awt.Font("Tahoma", 0, 16));

        jLabelNewName.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNewName.setText("New name              :");

        jPasswordFieldNewPassword.setFont(new java.awt.Font("Tahoma", 0, 16));
        jPasswordFieldNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldNewPasswordKeyReleased(evt);
            }
        });

        jLabelNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNewPassword.setText("New password        :");

        jPasswordFieldRePassword.setFont(new java.awt.Font("Tahoma", 0, 16));
        jPasswordFieldRePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldRePasswordKeyReleased(evt);
            }
        });

        jLabelRePassword.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelRePassword.setText("Re-type password  :");

        jButtonOk.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonOk.setText("OK");
        jButtonOk.setEnabled(false);
        jButtonOk.setFocusPainted(false);
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNewName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRePassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordFieldRePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPasswordFieldNewPassword)
                        .addComponent(jTextFieldNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNewPasswordStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRePasswordStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelNewPasswordStatus)
                        .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRePasswordStatus)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
    Password password = new Password();
    SystemInformation userCategory = new SystemInformation();
    
    //delete older file
    System.out.println("ChangePassword => "+userCategory.passwordFilePath);
    new File(userCategory.passwordFilePath).delete();
    
    //create new file
    String userPassword = new String(jPasswordFieldNewPassword.getPassword());
    String fileName = jTextFieldNewName.getText();
    if( userCategory.isJudge==true )
        fileName += ".jud";
    else
        fileName += ".con";
    System.out.println("ChangePassword => "+fileName+" "+userPassword);
    password.makeFile(fileName, userPassword);
    
    new MainPage().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButtonOkActionPerformed

private void jPasswordFieldRePasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldRePasswordKeyReleased
    if( checkPassword()==false ){
        jLabelRePasswordStatus.setForeground(Color.red);
        jLabelRePasswordStatus.setText("Not matched");
        jButtonOk.setEnabled(false);
    }
    else{
        jLabelRePasswordStatus.setForeground(Color.green);
        jLabelRePasswordStatus.setText("Matched");
        jButtonOk.setEnabled(true);
    }
}//GEN-LAST:event_jPasswordFieldRePasswordKeyReleased

private void jPasswordFieldNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldNewPasswordKeyReleased
    String userPassword = new String(jPasswordFieldNewPassword.getPassword());
    int security = 0;
    
    //length
    if( userPassword.length()>=6 )
        security++;
    //a to z
    if( checkString(userPassword, 'a', 'z')==true )
        security++;
    //A to Z
    if( checkString(userPassword, 'A', 'Z')==true )
        security++;
    //0 to 9
    if( checkString(userPassword, '0', '9')==true )
        security++;
    //punchuation
    for(int I=0; I<userPassword.length(); I++){
        char ch = userPassword.charAt(I);
        if( (ch<'a'||ch>'z')&&(ch<'A'||ch>'Z')&&(ch<'0'||ch>'9') ){
            security++;
            break;
        }
    }
    
    //show status
    if( security<=1 ){
        jLabelNewPasswordStatus.setForeground(Color.red);
        jLabelNewPasswordStatus.setText("Very poor");
    }
    else if( security==2 ){
        jLabelNewPasswordStatus.setForeground(Color.orange);
        jLabelNewPasswordStatus.setText("Poor");
    }
    else if( security==3 ){
        jLabelNewPasswordStatus.setForeground(Color.magenta);
        jLabelNewPasswordStatus.setText("Good");
    }
    else if( security==4 ){
        jLabelNewPasswordStatus.setForeground(Color.green);
        jLabelNewPasswordStatus.setText("Strong");
    }
    else if( security==5 ){
        jLabelNewPasswordStatus.setForeground(Color.blue);
        jLabelNewPasswordStatus.setText("Very strong");
    }
    
}//GEN-LAST:event_jPasswordFieldNewPasswordKeyReleased

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    new MainPage().setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PasswordChange().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelNewName;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelNewPasswordStatus;
    private javax.swing.JLabel jLabelRePassword;
    private javax.swing.JLabel jLabelRePasswordStatus;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JPasswordField jPasswordFieldRePassword;
    private javax.swing.JTextField jTextFieldNewName;
    // End of variables declaration//GEN-END:variables
}
