/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemoveProblemPage.java
 *
 * Created on Aug 22, 2012, 11:49:55 PM
 */
package pencon;

import javax.swing.JOptionPane;

/**
 *
 * @author RATUL
 */
public class RemoveProblemPage extends javax.swing.JDialog {

    /*updating new problem*/
    void removeProblem(){
        //if no problem is selected
        if( jComboBoxSelectProblem.getSelectedIndex()==0 )
            return ;
        
        //if one of problem is selected. determine problem id
        char problemId = (char)(jComboBoxSelectProblem.getSelectedIndex()-1+'A');
        ProblemSet problemSet = new ProblemSet();
        
        //remove the selected problem & rename other problem id if needed
        if( problemSet.removeProblem(problemId) ==true ){
            JOptionPane.showMessageDialog(rootPane, "Problem is removed from the problem set.", "Successful", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Error occured while deleting problem.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /** Creates new form RemoveProblemPage */
    public RemoveProblemPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        new ProblemSet().printProblemList(jComboBoxSelectProblem);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancel = new javax.swing.JButton();
        jComboBoxSelectProblem = new javax.swing.JComboBox();
        jLabelNameInputFile = new javax.swing.JLabel();
        jLabelMemoryLimitUnit = new javax.swing.JLabel();
        jLabelNameOutputFile = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jLabelTimeLimit = new javax.swing.JLabel();
        jTextFieldMemoryLimit = new javax.swing.JTextField();
        jTextFieldTimeLimit = new javax.swing.JTextField();
        jLabelTimeLimitUnit = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jLabelMemoryLimit = new javax.swing.JLabel();
        jTextFieldOutputFile = new javax.swing.JTextField();
        jLabelNameSelectProblem = new javax.swing.JLabel();
        jTextFieldInputFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove Problem");
        setResizable(false);

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboBoxSelectProblem.setFont(new java.awt.Font("Tahoma", 0, 14));
        jComboBoxSelectProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectProblemActionPerformed(evt);
            }
        });

        jLabelNameInputFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNameInputFile.setText("Input File        :");

        jLabelMemoryLimitUnit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelMemoryLimitUnit.setText("KB");

        jLabelNameOutputFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNameOutputFile.setText("Output File     :");

        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonDelete.setText("Delete");
        jButtonDelete.setFocusPainted(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelTimeLimit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelTimeLimit.setText("Time Limit      :");

        jTextFieldMemoryLimit.setEditable(false);
        jTextFieldMemoryLimit.setFont(new java.awt.Font("Tahoma", 0, 14));

        jTextFieldTimeLimit.setEditable(false);
        jTextFieldTimeLimit.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabelTimeLimitUnit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelTimeLimitUnit.setText("Sec");

        jTextFieldName.setEditable(false);
        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelName.setText("Name             :");

        jLabelMemoryLimit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelMemoryLimit.setText("Memory Limit :");

        jTextFieldOutputFile.setEditable(false);
        jTextFieldOutputFile.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabelNameSelectProblem.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelNameSelectProblem.setText("Select Problem :");

        jTextFieldInputFile.setEditable(false);
        jTextFieldInputFile.setFont(new java.awt.Font("Tahoma", 0, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNameInputFile)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNameSelectProblem)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxSelectProblem, 0, 230, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNameOutputFile)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTimeLimit)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTimeLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMemoryLimit)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMemoryLimitUnit)
                            .addComponent(jLabelTimeLimitUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNameSelectProblem)
                            .addComponent(jComboBoxSelectProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNameInputFile)
                            .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNameOutputFile)
                            .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTimeLimit)
                            .addComponent(jTextFieldTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelTimeLimitUnit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMemoryLimit)
                    .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMemoryLimitUnit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

private void jComboBoxSelectProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectProblemActionPerformed
    int selectedIndex = jComboBoxSelectProblem.getSelectedIndex();
    if( selectedIndex==0 ){
        jTextFieldName.setText(null);
        jTextFieldInputFile.setText(null);
        jTextFieldOutputFile.setText(null);
        jTextFieldTimeLimit.setText(null);
        jTextFieldMemoryLimit.setText(null);
        return ;
    }
    
    ProblemSet problemSet = new ProblemSet();
    char problemId = (char) (selectedIndex-1+'A');
    jTextFieldName.setText(problemSet.getProblemName(problemId));
    jTextFieldTimeLimit.setText(problemSet.getProblemTimeLimit(problemId));
    jTextFieldMemoryLimit.setText(problemSet.getProblemMemoryLimit(problemId));
    jTextFieldInputFile.setText(problemSet.isInputFileExists(problemId));
    jTextFieldOutputFile.setText(problemSet.isOutputFileExists(problemId));
    
}//GEN-LAST:event_jComboBoxSelectProblemActionPerformed

private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
    removeProblem();
}//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                RemoveProblemPage dialog = new RemoveProblemPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JComboBox jComboBoxSelectProblem;
    private javax.swing.JLabel jLabelMemoryLimit;
    private javax.swing.JLabel jLabelMemoryLimitUnit;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameInputFile;
    private javax.swing.JLabel jLabelNameOutputFile;
    private javax.swing.JLabel jLabelNameSelectProblem;
    private javax.swing.JLabel jLabelTimeLimit;
    private javax.swing.JLabel jLabelTimeLimitUnit;
    private javax.swing.JTextField jTextFieldInputFile;
    private javax.swing.JTextField jTextFieldMemoryLimit;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldOutputFile;
    private javax.swing.JTextField jTextFieldTimeLimit;
    // End of variables declaration//GEN-END:variables
}
