/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateProblemPage.java
 *
 * Created on Aug 23, 2012, 12:24:15 AM
 */
package pencon;

import javax.swing.JOptionPane;

/**
 *
 * @author RATUL
 */
public class UpdateProblemPage extends javax.swing.JDialog {

    /*updating new problem*/
    void updateProblem(){
        ProblemSet problemSet = new ProblemSet();
        
        //updating problem
        if( problemSet.addUpdateProblem((char)(jComboBoxSelectProblem.getSelectedIndex()-1+'A'), jTextFieldName.getText(), 
                jTextFieldInputFile.getText(), jTextFieldOutputFile.getText(), jTextFieldTimeLimit.getText(), 
                jTextFieldMemoryLimit.getText())==true ){
            JOptionPane.showMessageDialog(rootPane, "Problem is updated.", "Successful", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "You did not give correct information.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /** Creates new form UpdateProblemPage */
    public UpdateProblemPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        new ProblemSet().printProblemList(jComboBoxSelectProblem);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMemoryLimitUnit = new javax.swing.JLabel();
        jLabelMemoryLimit = new javax.swing.JLabel();
        jLabelTimeLimitUnit = new javax.swing.JLabel();
        jLabelTimeLimit = new javax.swing.JLabel();
        jButtonOutputFileBrwose = new javax.swing.JButton();
        jButtonInputFileBrwose = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabelNameOutputFile = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jLabelNameInputFile = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxSelectProblem = new javax.swing.JComboBox();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldMemoryLimit = new javax.swing.JTextField();
        jLabelNameSelectProblem = new javax.swing.JLabel();
        jTextFieldTimeLimit = new javax.swing.JTextField();
        jTextFieldOutputFile = new javax.swing.JTextField();
        jTextFieldInputFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update");
        setResizable(false);

        jLabelMemoryLimitUnit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelMemoryLimitUnit.setText("KB");

        jLabelMemoryLimit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelMemoryLimit.setText("Memory Limit :");

        jLabelTimeLimitUnit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelTimeLimitUnit.setText("Sec");

        jLabelTimeLimit.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelTimeLimit.setText("Time Limit      :");

        jButtonOutputFileBrwose.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButtonOutputFileBrwose.setText("Brwose");
        jButtonOutputFileBrwose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOutputFileBrwoseActionPerformed(evt);
            }
        });

        jButtonInputFileBrwose.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButtonInputFileBrwose.setText("Brwose");
        jButtonInputFileBrwose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInputFileBrwoseActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelName.setText("Name             :");

        jLabelNameOutputFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNameOutputFile.setText("Output File     :");

        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonSave.setText("Save");
        jButtonSave.setFocusPainted(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabelNameInputFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabelNameInputFile.setText("Input File        :");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14));

        jComboBoxSelectProblem.setFont(new java.awt.Font("Tahoma", 0, 14));
        jComboBoxSelectProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectProblemActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextFieldMemoryLimit.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabelNameSelectProblem.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabelNameSelectProblem.setText("Select Problem :");

        jTextFieldTimeLimit.setFont(new java.awt.Font("Tahoma", 0, 14));

        jTextFieldOutputFile.setFont(new java.awt.Font("Tahoma", 0, 14));

        jTextFieldInputFile.setFont(new java.awt.Font("Tahoma", 0, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMemoryLimit)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMemoryLimitUnit, 0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelTimeLimit)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabelTimeLimitUnit, 0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabelNameOutputFile)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonOutputFileBrwose)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelName)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelNameInputFile)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelNameSelectProblem)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxSelectProblem, 0, 179, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInputFileBrwose)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNameSelectProblem)
                    .addComponent(jComboBoxSelectProblem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameInputFile)
                    .addComponent(jTextFieldInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInputFileBrwose))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameOutputFile)
                    .addComponent(jTextFieldOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOutputFileBrwose))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTimeLimit)
                    .addComponent(jTextFieldTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTimeLimitUnit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMemoryLimit)
                    .addComponent(jTextFieldMemoryLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMemoryLimitUnit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonOutputFileBrwoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOutputFileBrwoseActionPerformed
    FileDirectory fileDirectory = new FileDirectory();
    String outPath = fileDirectory.selectFile("Select", "(output file)");
    jTextFieldOutputFile.setText(outPath);
}//GEN-LAST:event_jButtonOutputFileBrwoseActionPerformed

private void jButtonInputFileBrwoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputFileBrwoseActionPerformed
    FileDirectory fileDirectory = new FileDirectory();
    String inPath = fileDirectory.selectFile("Select", "(input file)");
    jTextFieldInputFile.setText(inPath);
}//GEN-LAST:event_jButtonInputFileBrwoseActionPerformed

private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
    updateProblem();
}//GEN-LAST:event_jButtonSaveActionPerformed

private void jComboBoxSelectProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectProblemActionPerformed
    int selectedIndex = jComboBoxSelectProblem.getSelectedIndex();
    if( selectedIndex==0 ){
        jTextFieldName.setText(null);
        jTextFieldInputFile.setText(null);
        jTextFieldOutputFile.setText(null);
        jTextFieldTimeLimit.setText(null);
        jTextFieldMemoryLimit.setText(null);
        return ;
    }
    
    ProblemSet problemSet = new ProblemSet();
    char problemId = (char) (selectedIndex-1+'A');
    jTextFieldName.setText(problemSet.getProblemName(problemId));
    jTextFieldTimeLimit.setText(problemSet.getProblemTimeLimit(problemId));
    jTextFieldMemoryLimit.setText(problemSet.getProblemMemoryLimit(problemId));
    jTextFieldInputFile.setText(problemSet.isInputFileExists(problemId));
    jTextFieldOutputFile.setText(problemSet.isOutputFileExists(problemId));
    
}//GEN-LAST:event_jComboBoxSelectProblemActionPerformed

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
   dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProblemPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UpdateProblemPage dialog = new UpdateProblemPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonInputFileBrwose;
    private javax.swing.JButton jButtonOutputFileBrwose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jComboBoxSelectProblem;
    private javax.swing.JLabel jLabelMemoryLimit;
    private javax.swing.JLabel jLabelMemoryLimitUnit;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameInputFile;
    private javax.swing.JLabel jLabelNameOutputFile;
    private javax.swing.JLabel jLabelNameSelectProblem;
    private javax.swing.JLabel jLabelTimeLimit;
    private javax.swing.JLabel jLabelTimeLimitUnit;
    private javax.swing.JTextField jTextFieldInputFile;
    private javax.swing.JTextField jTextFieldMemoryLimit;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldOutputFile;
    private javax.swing.JTextField jTextFieldTimeLimit;
    // End of variables declaration//GEN-END:variables
}
