/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserManual.java
 *
 * Created on Aug 23, 2012, 12:41:23 AM
 */
package pencon;

/**
 *
 * @author RATUL
 */
public class UserInstruction extends javax.swing.JDialog {

    /** Creates new form UserManual */
    public UserInstruction(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUserManual = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instruction");
        setResizable(false);

        jTextAreaUserManual.setBackground(new java.awt.Color(236, 233, 216));
        jTextAreaUserManual.setColumns(20);
        jTextAreaUserManual.setEditable(false);
        jTextAreaUserManual.setLineWrap(true);
        jTextAreaUserManual.setRows(5);
        jTextAreaUserManual.setText("\n Compiler \t: Select a compiler to run.\n\n Add File \t: Add a new file according to selected compiler.\n\n Manual Judge \t:\n\tCompile\t- Compile the added file. If you edit file on PenCon editor, then save it first before compile.\n\tRun\t- Run compiled file. Before running, you have to select an input file. If it does not need any input then select a empty/any ohter file.\n\tCheck \t- Compare the output file with other file (generally judge's output file). First, select a file for comparison.\n\n Auto Judge \t:\n\tfirst Arrange_Contest. \n\tSelect Problem\t- Select a problem before verdict.\n\tVerdict\t- Show the verdict of given file.\n\n Output\t: Show the output of the file that has been run & judge's output file including error if it has.\n\n Editable\t: Active/inactive PenCon editor to edit file.\n\n Result\t: Show the all submission result of a team including penalty time.\n\n Switch\t: Switching the user.\n\n\n Arrange_Contest :\n\tAdd New Problem\t- Add a new problem.\n\tUpdate Problem\t- Update a problem.\n\tRemove Problem\t- Remove a problem\n\tActive Contest\t\t- Activate contest on a pen drive.\n\tRanklist\t\t- Show the ranklist of a contest. (N.B.- Judge must have to seen result of all team before seeing ranklist.)\n");
        jTextAreaUserManual.setCaretColor(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(jTextAreaUserManual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInstruction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                UserInstruction dialog = new UserInstruction(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaUserManual;
    // End of variables declaration//GEN-END:variables
}
