/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaitForPenDrivePage.java
 *
 * Created on Aug 23, 2012, 12:04:42 AM
 */
package pencon;

import java.awt.Frame;
import java.io.File;

/**
 *
 * @author RATUL
 */
public class WaitForPenDrivePage extends javax.swing.JDialog implements Runnable {

    Frame predecessor = null;
    
    /** Creates new form WaitForPenDrivePage */
    public WaitForPenDrivePage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        predecessor = parent;
        
        new Thread(this).start();
    }
    
    public void run(){
        PenDriveDetection detectPenDrive = new PenDriveDetection();
        SystemInformation systemInformation = new SystemInformation();
        
        systemInformation.penDrive = detectPenDrive.getInsertedPenDriveName();
        
        //after detecting a pen drive
        jLabelWaitingImage.setEnabled(false);
        jLabelStatus.setText("Pen drive "+systemInformation.penDrive+" detected.");
        jLabelInstruction1.setText("All data will be remove from "+systemInformation.penDrive);
        jLabelInstruction2.setText("Are you sure you want to use it ?");
        jButtonYes.setEnabled(true);
        jButtonNo.setEnabled(true);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonYes = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jLabelWaitingImage = new javax.swing.JLabel();
        jLabelInstruction1 = new javax.swing.JLabel();
        jButtonNo = new javax.swing.JButton();
        jLabelInstruction2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Active Contest");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonYes.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonYes.setText("Yes");
        jButtonYes.setEnabled(false);
        jButtonYes.setFocusPainted(false);
        jButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYesActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabelStatus.setText("Please insert a pen drive.");

        jLabelWaitingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/waiting.gif"))); // NOI18N
        jLabelWaitingImage.setText("Waiting Image");

        jLabelInstruction1.setFont(new java.awt.Font("Tahoma", 2, 14));
        jLabelInstruction1.setText(" If it is already plugged in, first unplug it & then insert.");

        jButtonNo.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButtonNo.setText("No");
        jButtonNo.setEnabled(false);
        jButtonNo.setFocusPainted(false);
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoActionPerformed(evt);
            }
        });

        jLabelInstruction2.setFont(new java.awt.Font("Tahoma", 1, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInstruction2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelWaitingImage, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelStatus)
                            .addGap(136, 136, 136))
                        .addComponent(jLabelInstruction1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonYes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(15, 15, 15)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabelInstruction2)
                .addGap(52, 52, 52))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelWaitingImage)
                        .addComponent(jLabelStatus))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelInstruction1)
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonYes)
                        .addComponent(jButtonNo)
                        .addComponent(jButtonCancel))
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYesActionPerformed
    dispose();
    //if judge & not requested for result. 
    if( SystemInformation.isJudge==true && SystemInformation.isResult==false )
        new TeamInformation(predecessor, true).setVisible(true);
}//GEN-LAST:event_jButtonYesActionPerformed

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    //if cancelled pen drive detection then no pendrive will detected
    SystemInformation systemInformation = new SystemInformation();
    systemInformation.penDrive = null;
    dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

private void jButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoActionPerformed
    dispose();
    new WaitForPenDrivePage(predecessor, true).setVisible(true);
}//GEN-LAST:event_jButtonNoActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    SystemInformation systemInformation = new SystemInformation();
    systemInformation.penDrive = null;
}//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaitForPenDrivePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaitForPenDrivePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaitForPenDrivePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaitForPenDrivePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                WaitForPenDrivePage dialog = new WaitForPenDrivePage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JLabel jLabelInstruction1;
    private javax.swing.JLabel jLabelInstruction2;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelWaitingImage;
    // End of variables declaration//GEN-END:variables
}
